### ISSUE TITLE
Error in intro to portfolio review in vignette

### ISSUE THREAD

**Issue by adamlhayes** [ryscott5/eparTextTools#10]
Error thrown in the [Intro to portfolio review](https://github.com/ryscott5/eparTextTools/blob/master/vignettes/Intro_to_Portfolio_Review.Rmd) Line 191, using the word_heatmap function:

word_heatmap(tdm,pickwords=c("women","gender","access","land","right","work","labor","yield","security"))

Error in `[.simple_triplet_matrix`(termDocumentMatrix, pickwords, ) : Subscript out of bounds.

**Update**

This initial issue goes away when I download the entire repository (not sure why). Though, I'm still getting an error here:

BASE_INPUT<-PreTopicFrame2(corpus1,workingfolder=workingfolder)

Unequal factor levels: coercing to characterError in unique(fullorig$Orig) : object 'fullorig' not found

**Comment by Synaps3** [comment]
Hmm I'm pretty sure I didnt run into this error when I went thought it

**Comment by Synaps3** [comment]
I dont think I can reproduce either of these issues
