### ISSUE TITLE
tornadoCompare() returns an error

### ISSUE THREAD

**Issue by adamlhayes** [ryscott5/eparTextTools#18]
Running tornadoCompare returns the following error message when a tdm isn't saved as 'tdm':

Error in as.matrix(tdm[, as.vector(termmatrix[pickword, ]) <= frequency]) : 
  object 'tdm' not found

Should be an easy fix: just replace 'tdm' with 'termmatrix' in the function

**Comment by Synaps3** [comment]
Fixed. Checked in.
